var annotated_dup =
[
    [ "_lex_state_t", "struct__lex__state__t.html", null ],
    [ "_scpi_buffer_t", "struct__scpi__buffer__t.html", null ],
    [ "_scpi_choice_def_t", "struct__scpi__choice__def__t.html", null ],
    [ "_scpi_command_t", "struct__scpi__command__t.html", null ],
    [ "_scpi_const_buffer_t", "struct__scpi__const__buffer__t.html", null ],
    [ "_scpi_data_parameter_t", "struct__scpi__data__parameter__t.html", null ],
    [ "_scpi_error_info_heap_t", "struct__scpi__error__info__heap__t.html", null ],
    [ "_scpi_error_t", "struct__scpi__error__t.html", null ],
    [ "_scpi_fifo_t", "struct__scpi__fifo__t.html", null ],
    [ "_scpi_interface_t", "struct__scpi__interface__t.html", null ],
    [ "_scpi_number_parameter_t", "struct__scpi__number__parameter__t.html", null ],
    [ "_scpi_param_list_t", "struct__scpi__param__list__t.html", null ],
    [ "_scpi_parser_state_t", "struct__scpi__parser__state__t.html", null ],
    [ "_scpi_t", "struct__scpi__t.html", null ],
    [ "_scpi_token_t", "struct__scpi__token__t.html", null ],
    [ "_scpi_unit_def_t", "struct__scpi__unit__def__t.html", null ],
    [ "Channel", "class_channel.html", "class_channel" ],
    [ "CircularBuffer", "class_circular_buffer.html", "class_circular_buffer" ],
    [ "DDS_Channel", "class_d_d_s___channel.html", "class_d_d_s___channel" ],
    [ "DeviceCalibrationFactors", "struct_device_calibration_factors.html", "struct_device_calibration_factors" ],
    [ "DeviceClass", "class_device_class.html", "class_device_class" ],
    [ "DeviceVoltagesStruct", "struct_device_voltages_struct.html", "struct_device_voltages_struct" ],
    [ "DevSettingsEEPROMLayout", "struct_dev_settings_e_e_p_r_o_m_layout.html", "struct_dev_settings_e_e_p_r_o_m_layout" ],
    [ "DMM_Channel", "class_d_m_m___channel.html", "class_d_m_m___channel" ],
    [ "error_reg", "structerror__reg.html", null ],
    [ "ILI9341", "class_i_l_i9341.html", null ],
    [ "MCP23S08", "class_m_c_p23_s08.html", "class_m_c_p23_s08" ],
    [ "Parameter", "class_parameter.html", "class_parameter" ],
    [ "PS_Channel", "class_p_s___channel.html", "class_p_s___channel" ],
    [ "ScreenManagerClass", "class_screen_manager_class.html", "class_screen_manager_class" ],
    [ "UserInputData", "class_user_input_data.html", "class_user_input_data" ],
    [ "UserInputHandlerClass", "class_user_input_handler_class.html", "class_user_input_handler_class" ],
    [ "XPT2046", "class_x_p_t2046.html", "class_x_p_t2046" ]
];